// let's imagine this file is autogenerated from the backend
// ideally, we want to keep these api related types in sync
// with the backend instead of manually writing them out

import type {
  Education,
  Experience,
  Expertise,
  Language,
  ProfilePicture,
  SocialLinks,
} from '@/features/profile';

export type BaseEntity = {
  id: string;
  createdAt: number;
};

export type Entity<T> = {
  [K in keyof T]: T[K];
} & BaseEntity;

export type Meta = {
  page: number;
  total: number;
  totalPages: number;
};

export type User = {
  slug: string;
  firstName: string;
  lastName: string;
  email: string;
  profilePicture: ProfilePicture;
  status: Status;
  gender: 'Male' | 'Female';
  socialLinks: SocialLinks;
  bio: string;
  experiences: Experience[];
  educations: Education[];
  expertises: Expertise[];
  languages: Language[];
  profileCompletionStatus: number;
  // TODO  : add country !! country: string;
};

export type Status = {
  IsMentor: boolean;
  IsActive: boolean;
};

export type AuthResponse = {
  user: User;
};
