// let's imagine this file is autogenerated from the backend
// ideally, we want to keep these api related types in sync
// with the backend instead of manually writing them out

export type BaseEntity = {
  id: string;
  createdAt: number;
};

export type Entity<T> = {
  [K in keyof T]: T[K];
} & BaseEntity;

export type Meta = {
  page: number;
  total: number;
  totalPages: number;
};

export type User = {
  slug: string;
  firstName: string;
  lastName: string;
  email: string;
  status: Status;
  gender: 'Male' | 'Female';
  bio: string;
  integratedWithGoogle: boolean;
  googleEmail?: string | null;
  konnectWalletId?: string | null;
  roles: string[];
};

export type Status = {
  IsMentor: boolean;
  IsActive: boolean;
};

export type AuthResponse = {
  user: User;
};
