// <auto-generated />
using System;
using Booking.Modules.Users.Presistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Booking.Modules.Users.Persistence.Migrations
{
    [DbContext(typeof(UsersDbContext))]
    [Migration("20250830150406_KonnectWalletIdToUSersDbContext")]
    partial class KonnectWalletIdToUSersDbContext
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("users")
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Booking.Common.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on_utc");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_on_utc");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.ToTable("outbox_messages", "users");
                });

            modelBuilder.Entity("Booking.Modules.Users.Domain.EmailVerificationToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_utc");

                    b.Property<DateTime>("ExpiresOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_on_utc");

                    b.Property<Guid>("ExternalId")
                        .HasColumnType("uuid")
                        .HasColumnName("external_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_email_verification_token");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_email_verification_token_user_id");

                    b.ToTable("email_verification_token", "users");
                });

            modelBuilder.Entity("Booking.Modules.Users.Domain.Entities.Education", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("field");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<bool>("ToPresent")
                        .HasColumnType("boolean")
                        .HasColumnName("to_present");

                    b.Property<string>("University")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("university");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_educations");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_educations_user_id");

                    b.ToTable("educations", "users");
                });

            modelBuilder.Entity("Booking.Modules.Users.Domain.Entities.Experience", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("company");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("title");

                    b.Property<bool>("ToPresent")
                        .HasColumnType("boolean")
                        .HasColumnName("to_present");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_experiences");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_experiences_user_id");

                    b.ToTable("experiences", "users");
                });

            modelBuilder.Entity("Booking.Modules.Users.Domain.Entities.Expertise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_expertises");

                    b.ToTable("expertises", "users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 8, 30, 15, 4, 6, 99, DateTimeKind.Utc).AddTicks(6637),
                            Description = "Mentorship in web, backend, mobile, etc.",
                            Name = "Software Engineering",
                            UpdatedAt = new DateTime(2025, 8, 30, 15, 4, 6, 99, DateTimeKind.Utc).AddTicks(5338)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 8, 30, 15, 4, 6, 99, DateTimeKind.Utc).AddTicks(7054),
                            Description = "Mentorship in machines, manufacturing, CAD, etc.",
                            Name = "Mechanical Engineering",
                            UpdatedAt = new DateTime(2025, 8, 30, 15, 4, 6, 99, DateTimeKind.Utc).AddTicks(7051)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 8, 30, 15, 4, 6, 99, DateTimeKind.Utc).AddTicks(7056),
                            Description = "Mentorship in circuits, power systems, etc.",
                            Name = "Electrical Engineering",
                            UpdatedAt = new DateTime(2025, 8, 30, 15, 4, 6, 99, DateTimeKind.Utc).AddTicks(7056)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 8, 30, 15, 4, 6, 99, DateTimeKind.Utc).AddTicks(7059),
                            Description = "Mentorship in construction, infrastructure, etc.",
                            Name = "Civil Engineering",
                            UpdatedAt = new DateTime(2025, 8, 30, 15, 4, 6, 99, DateTimeKind.Utc).AddTicks(7058)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 8, 30, 15, 4, 6, 99, DateTimeKind.Utc).AddTicks(7061),
                            Description = "Mentorship in chemical processes, materials, etc.",
                            Name = "Chemical Engineering",
                            UpdatedAt = new DateTime(2025, 8, 30, 15, 4, 6, 99, DateTimeKind.Utc).AddTicks(7060)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 8, 30, 15, 4, 6, 99, DateTimeKind.Utc).AddTicks(7069),
                            Description = "Mentorship in aircraft, spacecraft, etc.",
                            Name = "Aerospace Engineering",
                            UpdatedAt = new DateTime(2025, 8, 30, 15, 4, 6, 99, DateTimeKind.Utc).AddTicks(7068)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 8, 30, 15, 4, 6, 99, DateTimeKind.Utc).AddTicks(7071),
                            Description = "Mentorship in sustainability, environment, etc.",
                            Name = "Environmental Engineering",
                            UpdatedAt = new DateTime(2025, 8, 30, 15, 4, 6, 99, DateTimeKind.Utc).AddTicks(7070)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2025, 8, 30, 15, 4, 6, 99, DateTimeKind.Utc).AddTicks(7073),
                            Description = "Frontend, backend, and fullstack web mentoring.",
                            Name = "Web Development",
                            UpdatedAt = new DateTime(2025, 8, 30, 15, 4, 6, 99, DateTimeKind.Utc).AddTicks(7072)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2025, 8, 30, 15, 4, 6, 99, DateTimeKind.Utc).AddTicks(7075),
                            Description = "Android, iOS, cross-platform app mentoring.",
                            Name = "Mobile Development",
                            UpdatedAt = new DateTime(2025, 8, 30, 15, 4, 6, 99, DateTimeKind.Utc).AddTicks(7074)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2025, 8, 30, 15, 4, 6, 99, DateTimeKind.Utc).AddTicks(7079),
                            Description = "Mentorship in data analysis, ML, statistics.",
                            Name = "Data Science",
                            UpdatedAt = new DateTime(2025, 8, 30, 15, 4, 6, 99, DateTimeKind.Utc).AddTicks(7078)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2025, 8, 30, 15, 4, 6, 99, DateTimeKind.Utc).AddTicks(7081),
                            Description = "Mentorship in ethical hacking, defense, etc.",
                            Name = "Cybersecurity",
                            UpdatedAt = new DateTime(2025, 8, 30, 15, 4, 6, 99, DateTimeKind.Utc).AddTicks(7080)
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2025, 8, 30, 15, 4, 6, 99, DateTimeKind.Utc).AddTicks(7083),
                            Description = "AWS, Azure, CI/CD, and infrastructure mentoring.",
                            Name = "Cloud & DevOps",
                            UpdatedAt = new DateTime(2025, 8, 30, 15, 4, 6, 99, DateTimeKind.Utc).AddTicks(7082)
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2025, 8, 30, 15, 4, 6, 99, DateTimeKind.Utc).AddTicks(7085),
                            Description = "Mentorship in ML models, AI theory, etc.",
                            Name = "AI & Machine Learning",
                            UpdatedAt = new DateTime(2025, 8, 30, 15, 4, 6, 99, DateTimeKind.Utc).AddTicks(7084)
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2025, 8, 30, 15, 4, 6, 99, DateTimeKind.Utc).AddTicks(7087),
                            Description = "Mentorship in user experience and interface design.",
                            Name = "UI/UX Design",
                            UpdatedAt = new DateTime(2025, 8, 30, 15, 4, 6, 99, DateTimeKind.Utc).AddTicks(7086)
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2025, 8, 30, 15, 4, 6, 99, DateTimeKind.Utc).AddTicks(7089),
                            Description = "Mentorship for startup founders and entrepreneurs.",
                            Name = "Startup Coaching",
                            UpdatedAt = new DateTime(2025, 8, 30, 15, 4, 6, 99, DateTimeKind.Utc).AddTicks(7088)
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2025, 8, 30, 15, 4, 6, 99, DateTimeKind.Utc).AddTicks(7091),
                            Description = "Mentorship in business models and scaling.",
                            Name = "Business Strategy",
                            UpdatedAt = new DateTime(2025, 8, 30, 15, 4, 6, 99, DateTimeKind.Utc).AddTicks(7090)
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2025, 8, 30, 15, 4, 6, 99, DateTimeKind.Utc).AddTicks(7093),
                            Description = "Mentorship in digital marketing, social media, etc.",
                            Name = "Marketing & Branding",
                            UpdatedAt = new DateTime(2025, 8, 30, 15, 4, 6, 99, DateTimeKind.Utc).AddTicks(7092)
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2025, 8, 30, 15, 4, 6, 99, DateTimeKind.Utc).AddTicks(7097),
                            Description = "Mentorship in B2B, B2C, pitching, etc.",
                            Name = "Sales",
                            UpdatedAt = new DateTime(2025, 8, 30, 15, 4, 6, 99, DateTimeKind.Utc).AddTicks(7096)
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2025, 8, 30, 15, 4, 6, 99, DateTimeKind.Utc).AddTicks(7099),
                            Description = "Mentorship in online business and marketplaces.",
                            Name = "E-commerce",
                            UpdatedAt = new DateTime(2025, 8, 30, 15, 4, 6, 99, DateTimeKind.Utc).AddTicks(7098)
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2025, 8, 30, 15, 4, 6, 99, DateTimeKind.Utc).AddTicks(7101),
                            Description = "Mentorship in product lifecycle, agile, etc.",
                            Name = "Product Management",
                            UpdatedAt = new DateTime(2025, 8, 30, 15, 4, 6, 99, DateTimeKind.Utc).AddTicks(7100)
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2025, 8, 30, 15, 4, 6, 99, DateTimeKind.Utc).AddTicks(7103),
                            Description = "Mentorship in managing teams and tasks.",
                            Name = "Project Management",
                            UpdatedAt = new DateTime(2025, 8, 30, 15, 4, 6, 99, DateTimeKind.Utc).AddTicks(7102)
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2025, 8, 30, 15, 4, 6, 99, DateTimeKind.Utc).AddTicks(7105),
                            Description = "Mentorship in stocks, real estate, etc.",
                            Name = "Investment",
                            UpdatedAt = new DateTime(2025, 8, 30, 15, 4, 6, 99, DateTimeKind.Utc).AddTicks(7104)
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2025, 8, 30, 15, 4, 6, 99, DateTimeKind.Utc).AddTicks(7107),
                            Description = "Budgeting, saving, financial planning.",
                            Name = "Personal Finance",
                            UpdatedAt = new DateTime(2025, 8, 30, 15, 4, 6, 99, DateTimeKind.Utc).AddTicks(7106)
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2025, 8, 30, 15, 4, 6, 99, DateTimeKind.Utc).AddTicks(7109),
                            Description = "Corporate and freelance financial help.",
                            Name = "Accounting & Auditing",
                            UpdatedAt = new DateTime(2025, 8, 30, 15, 4, 6, 99, DateTimeKind.Utc).AddTicks(7108)
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2025, 8, 30, 15, 4, 6, 99, DateTimeKind.Utc).AddTicks(7111),
                            Description = "Medical school and residency mentorship.",
                            Name = "General Medicine",
                            UpdatedAt = new DateTime(2025, 8, 30, 15, 4, 6, 99, DateTimeKind.Utc).AddTicks(7110)
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2025, 8, 30, 15, 4, 6, 99, DateTimeKind.Utc).AddTicks(7113),
                            Description = "Clinical mentorship and nursing school support.",
                            Name = "Nursing",
                            UpdatedAt = new DateTime(2025, 8, 30, 15, 4, 6, 99, DateTimeKind.Utc).AddTicks(7112)
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2025, 8, 30, 15, 4, 6, 99, DateTimeKind.Utc).AddTicks(7115),
                            Description = "Pharmaceutical career and education guidance.",
                            Name = "Pharmacy",
                            UpdatedAt = new DateTime(2025, 8, 30, 15, 4, 6, 99, DateTimeKind.Utc).AddTicks(7114)
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2025, 8, 30, 15, 4, 6, 99, DateTimeKind.Utc).AddTicks(7117),
                            Description = "Psychology, therapy, and emotional support.",
                            Name = "Mental Health",
                            UpdatedAt = new DateTime(2025, 8, 30, 15, 4, 6, 99, DateTimeKind.Utc).AddTicks(7117)
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2025, 8, 30, 15, 4, 6, 99, DateTimeKind.Utc).AddTicks(7119),
                            Description = "Mentorship in epidemiology, policy, etc.",
                            Name = "Public Health",
                            UpdatedAt = new DateTime(2025, 8, 30, 15, 4, 6, 99, DateTimeKind.Utc).AddTicks(7119)
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2025, 8, 30, 15, 4, 6, 99, DateTimeKind.Utc).AddTicks(7121),
                            Description = "Mentorship in contracts, companies, etc.",
                            Name = "Corporate Law",
                            UpdatedAt = new DateTime(2025, 8, 30, 15, 4, 6, 99, DateTimeKind.Utc).AddTicks(7121)
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTime(2025, 8, 30, 15, 4, 6, 99, DateTimeKind.Utc).AddTicks(7174),
                            Description = "Legal career coaching in criminal justice.",
                            Name = "Criminal Law",
                            UpdatedAt = new DateTime(2025, 8, 30, 15, 4, 6, 99, DateTimeKind.Utc).AddTicks(7173)
                        },
                        new
                        {
                            Id = 32,
                            CreatedAt = new DateTime(2025, 8, 30, 15, 4, 6, 99, DateTimeKind.Utc).AddTicks(7176),
                            Description = "Mentorship in visa and immigration processes.",
                            Name = "Immigration Law",
                            UpdatedAt = new DateTime(2025, 8, 30, 15, 4, 6, 99, DateTimeKind.Utc).AddTicks(7176)
                        },
                        new
                        {
                            Id = 33,
                            CreatedAt = new DateTime(2025, 8, 30, 15, 4, 6, 99, DateTimeKind.Utc).AddTicks(7179),
                            Description = "Mentorship in patents, copyrights, etc.",
                            Name = "Intellectual Property Law",
                            UpdatedAt = new DateTime(2025, 8, 30, 15, 4, 6, 99, DateTimeKind.Utc).AddTicks(7178)
                        },
                        new
                        {
                            Id = 34,
                            CreatedAt = new DateTime(2025, 8, 30, 15, 4, 6, 99, DateTimeKind.Utc).AddTicks(7183),
                            Description = "Mentorship in team building and leading.",
                            Name = "Leadership & Management",
                            UpdatedAt = new DateTime(2025, 8, 30, 15, 4, 6, 99, DateTimeKind.Utc).AddTicks(7182)
                        },
                        new
                        {
                            Id = 35,
                            CreatedAt = new DateTime(2025, 8, 30, 15, 4, 6, 99, DateTimeKind.Utc).AddTicks(7185),
                            Description = "Mentorship in effective communication.",
                            Name = "Communication Skills",
                            UpdatedAt = new DateTime(2025, 8, 30, 15, 4, 6, 99, DateTimeKind.Utc).AddTicks(7184)
                        },
                        new
                        {
                            Id = 36,
                            CreatedAt = new DateTime(2025, 8, 30, 15, 4, 6, 99, DateTimeKind.Utc).AddTicks(7187),
                            Description = "Coaching on personal productivity.",
                            Name = "Time Management",
                            UpdatedAt = new DateTime(2025, 8, 30, 15, 4, 6, 99, DateTimeKind.Utc).AddTicks(7186)
                        },
                        new
                        {
                            Id = 37,
                            CreatedAt = new DateTime(2025, 8, 30, 15, 4, 6, 99, DateTimeKind.Utc).AddTicks(7189),
                            Description = "Confidence building and speech coaching.",
                            Name = "Public Speaking",
                            UpdatedAt = new DateTime(2025, 8, 30, 15, 4, 6, 99, DateTimeKind.Utc).AddTicks(7188)
                        },
                        new
                        {
                            Id = 38,
                            CreatedAt = new DateTime(2025, 8, 30, 15, 4, 6, 99, DateTimeKind.Utc).AddTicks(7191),
                            Description = "Mock interviews and job prep.",
                            Name = "Job Interview Coaching",
                            UpdatedAt = new DateTime(2025, 8, 30, 15, 4, 6, 99, DateTimeKind.Utc).AddTicks(7190)
                        },
                        new
                        {
                            Id = 39,
                            CreatedAt = new DateTime(2025, 8, 30, 15, 4, 6, 99, DateTimeKind.Utc).AddTicks(7193),
                            Description = "Profile and resume optimization.",
                            Name = "Resume & LinkedIn Review",
                            UpdatedAt = new DateTime(2025, 8, 30, 15, 4, 6, 99, DateTimeKind.Utc).AddTicks(7192)
                        },
                        new
                        {
                            Id = 40,
                            CreatedAt = new DateTime(2025, 8, 30, 15, 4, 6, 99, DateTimeKind.Utc).AddTicks(7195),
                            Description = "Long-term goal mentorship.",
                            Name = "Career Planning",
                            UpdatedAt = new DateTime(2025, 8, 30, 15, 4, 6, 99, DateTimeKind.Utc).AddTicks(7194)
                        },
                        new
                        {
                            Id = 41,
                            CreatedAt = new DateTime(2025, 8, 30, 15, 4, 6, 99, DateTimeKind.Utc).AddTicks(7197),
                            Description = "Mentorship in tools like Photoshop, Figma.",
                            Name = "Graphic Design",
                            UpdatedAt = new DateTime(2025, 8, 30, 15, 4, 6, 99, DateTimeKind.Utc).AddTicks(7196)
                        },
                        new
                        {
                            Id = 42,
                            CreatedAt = new DateTime(2025, 8, 30, 15, 4, 6, 99, DateTimeKind.Utc).AddTicks(7199),
                            Description = "Camera use, editing, and career advice.",
                            Name = "Photography",
                            UpdatedAt = new DateTime(2025, 8, 30, 15, 4, 6, 99, DateTimeKind.Utc).AddTicks(7198)
                        },
                        new
                        {
                            Id = 43,
                            CreatedAt = new DateTime(2025, 8, 30, 15, 4, 6, 99, DateTimeKind.Utc).AddTicks(7201),
                            Description = "Mentorship in composition, mixing, etc.",
                            Name = "Music Production",
                            UpdatedAt = new DateTime(2025, 8, 30, 15, 4, 6, 99, DateTimeKind.Utc).AddTicks(7200)
                        },
                        new
                        {
                            Id = 44,
                            CreatedAt = new DateTime(2025, 8, 30, 15, 4, 6, 99, DateTimeKind.Utc).AddTicks(7203),
                            Description = "Mentorship in writing books or articles.",
                            Name = "Writing & Publishing",
                            UpdatedAt = new DateTime(2025, 8, 30, 15, 4, 6, 99, DateTimeKind.Utc).AddTicks(7202)
                        },
                        new
                        {
                            Id = 45,
                            CreatedAt = new DateTime(2025, 8, 30, 15, 4, 6, 99, DateTimeKind.Utc).AddTicks(7205),
                            Description = "Mentorship in Premiere Pro, storytelling, etc.",
                            Name = "Video Editing",
                            UpdatedAt = new DateTime(2025, 8, 30, 15, 4, 6, 99, DateTimeKind.Utc).AddTicks(7205)
                        },
                        new
                        {
                            Id = 46,
                            CreatedAt = new DateTime(2025, 8, 30, 15, 4, 6, 99, DateTimeKind.Utc).AddTicks(7207),
                            Description = "Unity, Unreal, and career mentorship.",
                            Name = "Game Development",
                            UpdatedAt = new DateTime(2025, 8, 30, 15, 4, 6, 99, DateTimeKind.Utc).AddTicks(7207)
                        },
                        new
                        {
                            Id = 47,
                            CreatedAt = new DateTime(2025, 8, 30, 15, 4, 6, 99, DateTimeKind.Utc).AddTicks(7209),
                            Description = "Mentorship for language fluency.",
                            Name = "Language Learning",
                            UpdatedAt = new DateTime(2025, 8, 30, 15, 4, 6, 99, DateTimeKind.Utc).AddTicks(7209)
                        },
                        new
                        {
                            Id = 48,
                            CreatedAt = new DateTime(2025, 8, 30, 15, 4, 6, 99, DateTimeKind.Utc).AddTicks(7211),
                            Description = "Mentorship for international students.",
                            Name = "Study Abroad Guidance",
                            UpdatedAt = new DateTime(2025, 8, 30, 15, 4, 6, 99, DateTimeKind.Utc).AddTicks(7211)
                        },
                        new
                        {
                            Id = 49,
                            CreatedAt = new DateTime(2025, 8, 30, 15, 4, 6, 99, DateTimeKind.Utc).AddTicks(7214),
                            Description = "Mentorship in motivation, habits, etc.",
                            Name = "Life Coaching",
                            UpdatedAt = new DateTime(2025, 8, 30, 15, 4, 6, 99, DateTimeKind.Utc).AddTicks(7213)
                        },
                        new
                        {
                            Id = 50,
                            CreatedAt = new DateTime(2025, 8, 30, 15, 4, 6, 99, DateTimeKind.Utc).AddTicks(7216),
                            Description = "System building, discipline, deep work.",
                            Name = "Productivity Coaching",
                            UpdatedAt = new DateTime(2025, 8, 30, 15, 4, 6, 99, DateTimeKind.Utc).AddTicks(7215)
                        });
                });

            modelBuilder.Entity("Booking.Modules.Users.Domain.Entities.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_languages");

                    b.ToTable("languages", "users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 8, 30, 15, 4, 6, 100, DateTimeKind.Utc).AddTicks(6378),
                            Name = "English",
                            UpdatedAt = new DateTime(2025, 8, 30, 15, 4, 6, 100, DateTimeKind.Utc).AddTicks(5746)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 8, 30, 15, 4, 6, 100, DateTimeKind.Utc).AddTicks(6402),
                            Name = "French",
                            UpdatedAt = new DateTime(2025, 8, 30, 15, 4, 6, 100, DateTimeKind.Utc).AddTicks(6400)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 8, 30, 15, 4, 6, 100, DateTimeKind.Utc).AddTicks(6404),
                            Name = "Arabic",
                            UpdatedAt = new DateTime(2025, 8, 30, 15, 4, 6, 100, DateTimeKind.Utc).AddTicks(6403)
                        });
                });

            modelBuilder.Entity("Booking.Modules.Users.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedByIp")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by_ip");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_utc");

                    b.Property<DateTime>("ExpiresOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_on_utc");

                    b.Property<Guid>("ExternalId")
                        .HasColumnType("uuid")
                        .HasColumnName("external_id");

                    b.Property<DateTime?>("RevokedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_on_utc");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_agent");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("ExternalId")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_external_id");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens", "users");
                });

            modelBuilder.Entity("Booking.Modules.Users.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("Bio")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("bio");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("gender");

                    b.Property<string>("GoogleEmail")
                        .HasColumnType("text")
                        .HasColumnName("google_email");

                    b.Property<bool>("IntegratedWithGoogle")
                        .HasColumnType("boolean")
                        .HasColumnName("integrated_with_google");

                    b.Property<string>("KonnectWalledId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("konnect_walled_id");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<string>("TimezoneId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("timezone_id");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_users");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_asp_net_users_slug");

                    b.ToTable("AspNetUsers", "users");
                });

            modelBuilder.Entity("Booking.Modules.Users.Domain.JoinTables.MentorMentee", b =>
                {
                    b.Property<int>("MentorId")
                        .HasColumnType("integer")
                        .HasColumnName("mentor_id");

                    b.Property<int>("MenteeId")
                        .HasColumnType("integer")
                        .HasColumnName("mentee_id");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_utc");

                    b.HasKey("MentorId", "MenteeId")
                        .HasName("pk_user_mentors");

                    b.HasIndex("MenteeId")
                        .HasDatabaseName("ix_user_mentors_mentee_id");

                    b.ToTable("user_mentors", "users");
                });

            modelBuilder.Entity("Booking.Modules.Users.Domain.JoinTables.UserExpertise", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int>("ExpertiseId")
                        .HasColumnType("integer")
                        .HasColumnName("expertise_id");

                    b.HasKey("UserId", "ExpertiseId")
                        .HasName("pk_user_expertises");

                    b.HasIndex("ExpertiseId")
                        .HasDatabaseName("ix_user_expertises_expertise_id");

                    b.ToTable("user_expertises", "users");
                });

            modelBuilder.Entity("Booking.Modules.Users.Domain.JoinTables.UserLanguage", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int>("LanguageId")
                        .HasColumnType("integer")
                        .HasColumnName("language_id");

                    b.HasKey("UserId", "LanguageId")
                        .HasName("pk_user_languages");

                    b.HasIndex("LanguageId")
                        .HasDatabaseName("ix_user_languages_language_id");

                    b.ToTable("user_languages", "users");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_roles");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", "users");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_role_claims");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_role_claims_role_id");

                    b.ToTable("AspNetRoleClaims", "users");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_claims_user_id");

                    b.ToTable("AspNetUserClaims", "users");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_asp_net_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_logins_user_id");

                    b.ToTable("AspNetUserLogins", "users");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_asp_net_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_user_roles_role_id");

                    b.ToTable("AspNetUserRoles", "users");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_asp_net_user_tokens");

                    b.ToTable("AspNetUserTokens", "users");
                });

            modelBuilder.Entity("Booking.Modules.Users.Domain.EmailVerificationToken", b =>
                {
                    b.HasOne("Booking.Modules.Users.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_email_verification_token_asp_net_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Booking.Modules.Users.Domain.Entities.Education", b =>
                {
                    b.HasOne("Booking.Modules.Users.Domain.Entities.User", "User")
                        .WithMany("Educations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_educations_user_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Booking.Modules.Users.Domain.Entities.Experience", b =>
                {
                    b.HasOne("Booking.Modules.Users.Domain.Entities.User", "User")
                        .WithMany("Experiences")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_experiences_user_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Booking.Modules.Users.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("Booking.Modules.Users.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_user_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Booking.Modules.Users.Domain.Entities.User", b =>
                {
                    b.OwnsOne("Booking.Modules.Users.Domain.ValueObjects.Name", "Name", b1 =>
                        {
                            b1.Property<int>("UserId")
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("name_first_name");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("name_last_name");

                            b1.HasKey("UserId");

                            b1.ToTable("AspNetUsers", "users");

                            b1.WithOwner()
                                .HasForeignKey("UserId")
                                .HasConstraintName("fk_asp_net_users_asp_net_users_id");
                        });

                    b.OwnsOne("Booking.Modules.Users.Domain.ValueObjects.ProfileCompletionStatus", "ProfileCompletionStatus", b1 =>
                        {
                            b1.Property<int>("UserId")
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            b1.Property<int>("CompletionStatus")
                                .HasColumnType("integer")
                                .HasColumnName("profile_completion_status_completion_status");

                            b1.Property<bool>("HasBio")
                                .HasColumnType("boolean")
                                .HasColumnName("profile_completion_status_has_bio");

                            b1.Property<bool>("HasConnectedWithGoogle")
                                .HasColumnType("boolean")
                                .HasColumnName("profile_completion_status_has_connected_with_google");

                            b1.Property<bool>("HasEducation")
                                .HasColumnType("boolean")
                                .HasColumnName("profile_completion_status_has_education");

                            b1.Property<bool>("HasExperience")
                                .HasColumnType("boolean")
                                .HasColumnName("profile_completion_status_has_experience");

                            b1.Property<bool>("HasExpertise")
                                .HasColumnType("boolean")
                                .HasColumnName("profile_completion_status_has_expertise");

                            b1.Property<bool>("HasLanguages")
                                .HasColumnType("boolean")
                                .HasColumnName("profile_completion_status_has_languages");

                            b1.Property<bool>("HasProfilePicture")
                                .HasColumnType("boolean")
                                .HasColumnName("profile_completion_status_has_profile_picture");

                            b1.Property<bool>("HasSocialLinks")
                                .HasColumnType("boolean")
                                .HasColumnName("profile_completion_status_has_social_links");

                            b1.Property<int>("TotalFields")
                                .HasColumnType("integer")
                                .HasColumnName("profile_completion_status_total_fields");

                            b1.HasKey("UserId");

                            b1.ToTable("AspNetUsers", "users");

                            b1.WithOwner()
                                .HasForeignKey("UserId")
                                .HasConstraintName("fk_asp_net_users_asp_net_users_id");
                        });

                    b.OwnsOne("Booking.Modules.Users.Domain.ValueObjects.ProfilePicture", "ProfilePictureUrl", b1 =>
                        {
                            b1.Property<int>("UserId")
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            b1.Property<string>("ProfilePictureLink")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("profile_picture_url_profile_picture_link");

                            b1.Property<string>("ThumbnailUrlPictureLink")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("profile_picture_url_thumbnail_url_picture_link");

                            b1.HasKey("UserId");

                            b1.ToTable("AspNetUsers", "users");

                            b1.WithOwner()
                                .HasForeignKey("UserId")
                                .HasConstraintName("fk_asp_net_users_asp_net_users_id");
                        });

                    b.OwnsOne("Booking.Modules.Users.Domain.ValueObjects.SocialLinks", "SocialLinks", b1 =>
                        {
                            b1.Property<int>("UserId")
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            b1.Property<string>("Facebook")
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("social_links_facebook");

                            b1.Property<string>("Github")
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("social_links_github");

                            b1.Property<string>("Instagram")
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("social_links_instagram");

                            b1.Property<string>("LinkedIn")
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("social_links_linked_in");

                            b1.Property<string>("Portfolio")
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("social_links_portfolio");

                            b1.Property<string>("Twitter")
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("social_links_twitter");

                            b1.Property<string>("Youtube")
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("social_links_youtube");

                            b1.HasKey("UserId");

                            b1.ToTable("AspNetUsers", "users");

                            b1.WithOwner()
                                .HasForeignKey("UserId")
                                .HasConstraintName("fk_asp_net_users_asp_net_users_id");
                        });

                    b.OwnsOne("Booking.Modules.Users.Domain.ValueObjects.Status", "Status", b1 =>
                        {
                            b1.Property<int>("UserId")
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            b1.Property<bool>("IsActive")
                                .HasColumnType("boolean")
                                .HasColumnName("status_is_active");

                            b1.Property<bool>("IsMentor")
                                .HasColumnType("boolean")
                                .HasColumnName("status_is_mentor");

                            b1.HasKey("UserId");

                            b1.ToTable("AspNetUsers", "users");

                            b1.WithOwner()
                                .HasForeignKey("UserId")
                                .HasConstraintName("fk_asp_net_users_asp_net_users_id");
                        });

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("ProfileCompletionStatus")
                        .IsRequired();

                    b.Navigation("ProfilePictureUrl")
                        .IsRequired();

                    b.Navigation("SocialLinks")
                        .IsRequired();

                    b.Navigation("Status")
                        .IsRequired();
                });

            modelBuilder.Entity("Booking.Modules.Users.Domain.JoinTables.MentorMentee", b =>
                {
                    b.HasOne("Booking.Modules.Users.Domain.Entities.User", "Mentee")
                        .WithMany("UserMentors")
                        .HasForeignKey("MenteeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_mentors_asp_net_users_mentee_id");

                    b.HasOne("Booking.Modules.Users.Domain.Entities.User", "Mentor")
                        .WithMany("UserMentees")
                        .HasForeignKey("MentorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_mentors_asp_net_users_mentor_id");

                    b.Navigation("Mentee");

                    b.Navigation("Mentor");
                });

            modelBuilder.Entity("Booking.Modules.Users.Domain.JoinTables.UserExpertise", b =>
                {
                    b.HasOne("Booking.Modules.Users.Domain.Entities.Expertise", "Expertise")
                        .WithMany("UserExpertises")
                        .HasForeignKey("ExpertiseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_expertises_expertises_expertise_id");

                    b.HasOne("Booking.Modules.Users.Domain.Entities.User", "User")
                        .WithMany("UserExpertises")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_expertises_user_user_id");

                    b.Navigation("Expertise");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Booking.Modules.Users.Domain.JoinTables.UserLanguage", b =>
                {
                    b.HasOne("Booking.Modules.Users.Domain.Entities.Language", "Language")
                        .WithMany("UserLanguages")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_languages_languages_language_id");

                    b.HasOne("Booking.Modules.Users.Domain.Entities.User", "User")
                        .WithMany("UserLanguages")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_languages_user_user_id");

                    b.Navigation("Language");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_role_claims_asp_net_roles_role_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("Booking.Modules.Users.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_claims_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("Booking.Modules.Users.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_logins_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_roles_role_id");

                    b.HasOne("Booking.Modules.Users.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("Booking.Modules.Users.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_tokens_asp_net_users_user_id");
                });

            modelBuilder.Entity("Booking.Modules.Users.Domain.Entities.Expertise", b =>
                {
                    b.Navigation("UserExpertises");
                });

            modelBuilder.Entity("Booking.Modules.Users.Domain.Entities.Language", b =>
                {
                    b.Navigation("UserLanguages");
                });

            modelBuilder.Entity("Booking.Modules.Users.Domain.Entities.User", b =>
                {
                    b.Navigation("Educations");

                    b.Navigation("Experiences");

                    b.Navigation("UserExpertises");

                    b.Navigation("UserLanguages");

                    b.Navigation("UserMentees");

                    b.Navigation("UserMentors");
                });
#pragma warning restore 612, 618
        }
    }
}
