export type EducationType = {
  id?: number; // Optional for new entries : automatically generated by db
  field: string;
  description: string;
  startDate: Date;
  endDate?: Date | null;
  university: string;
  toPresent?: boolean; // automatically set to false if endDate is provided
  userId?: number; // automatically passed by the cookies
};
